import Head from "next/head";

export async function getServerSideProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await res.json();
  return {
    props: {
      todos: data,
    },
  };
}

type TodoProp = {
  id: number;
  title: string;
};

export default function Home({ todos }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {todos?.length === 0 ? (
        <div>loading ...</div>
      ) : (
        todos?.map((todo: TodoProp) => (
          <div key={todo?.id}>
            <p>
              {todo?.id} : {todo?.title}
            </p>
          </div>
        ))
      )}
    </>
  );
}
